<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('posts')->delete();
        
        \DB::table('posts')->insert(array (
            0 => 
            array (
                'id' => '013f7600-5d23-11e8-b9db-0790bff71e16',
                'name' => 'Gods Gift',
                'section' => 'product',
                'slug' => 'chronic-pain-relief-center-gods-gift',
                'avatar' => NULL,
                'featured_img' => 'uploads/products/featured/Ufe3DlP9swhEYulg8L0ORaoTedVhUTSg9cmhg06n.jpeg',
                'description' => NULL,
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => NULL,
                'state' => NULL,
                'city' => NULL,
                'postal_code' => NULL,
                'country' => NULL,
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 18:15:56',
                'updated_at' => '2018-05-21 18:15:57',
            ),
            1 => 
            array (
                'id' => '045afdc0-5d24-11e8-abcb-01ee695a162f',
                'name' => 'Paris OG',
                'section' => 'product',
                'slug' => 'chronic-pain-relief-center-paris-og',
                'avatar' => NULL,
                'featured_img' => 'uploads/products/featured/lhWK6hpMVe0Y4m8P8AVZLo5ih7RSCM3IkpxPw1cr.jpeg',
                'description' => NULL,
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => NULL,
                'state' => NULL,
                'city' => NULL,
                'postal_code' => NULL,
                'country' => NULL,
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 18:23:10',
                'updated_at' => '2018-05-21 18:23:12',
            ),
            2 => 
            array (
                'id' => '0640ffa0-5b9f-11e8-9a04-5daa7a6f5bed',
                'name' => 'The Green Easy',
                'section' => 'shop',
                'slug' => 'the-green-easy',
                'avatar' => 'uploads/business/avatars/shops/m0oxDc3UeKHcouQvabdEuMU1GLBMn5QhebAETw5N.jpeg',
                'featured_img' => 'uploads/business/featured/shops/OJ2RC8vGesK1zf7nZbSKQtGKkNBtCPIp4P7pgCYH.jpeg',
                'description' => 'Est.2009. The Green Easy is your premier marijuana dispensary in Los Angeles. There are many dispensaries out there but none offer the service and quality medication that we have at The Green Easy. Our staff will work with you to get the best product to fit your needs. We have a large variety of products including edibles, concentrates, vape cartridges, and the best quality marijuana available. We work hard to get the best products and the best strains in our shop and as a result our menu always has something new to try. We have the quality products that you can\'t get from your average dispensary in Los Angeles. We always make it our goal to provide the best customer service possible.',
                'latitude' => '34.0763234',
                'longitude' => '-118.3704601',
                'address' => '8311 Beverly Boulevard',
                'state' => 'California',
                'city' => 'Los Angeles',
                'postal_code' => '90048-2607',
                'country' => 'United States',
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-19 19:58:39',
                'updated_at' => '2018-05-19 19:58:41',
            ),
            3 => 
            array (
                'id' => '08581810-5d23-11e8-a0ab-63806e45146c',
                'name' => 'Death OG',
                'section' => 'product',
                'slug' => 'chronic-pain-relief-center-death-og',
                'avatar' => NULL,
                'featured_img' => 'uploads/products/featured/MEtfyfAuTvi0idr3PHhj3fEQwohwsJy7WvgCFASx.jpeg',
                'description' => NULL,
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => NULL,
                'state' => NULL,
                'city' => NULL,
                'postal_code' => NULL,
                'country' => NULL,
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 18:16:08',
                'updated_at' => '2018-05-21 18:16:09',
            ),
            4 => 
            array (
                'id' => '09e4b270-5c99-11e8-aaf1-cd90abb01fbb',
                'name' => 'AHHS WEST HOLLYWOOD',
                'section' => 'shop',
                'slug' => 'ahhs-west-hollywood',
                'avatar' => 'uploads/business/avatars/shops/fHgN3Pbftxihgm0UauAFRqNuqfpfSm8FMU28tyxR.jpeg',
                'featured_img' => 'uploads/business/featured/shops/igoyQchXvHAanXT5EwsTrUzd3eE9JcIdJ8hT62Jx.jpeg',
                'description' => 'We first opened our doors to patients and the community in 2004,
Alternative Herbal Health Services is officially licensed for Adult use and medical marijuana sales. 

NEW DAILY SPECIALS 



MANIC MONDAY 

PRE ROLLS 10% OFF



TOPICAL TUESDAY 

TOPICALS AND TINCTURES 10% OFF



WONDERFUL WEDNESDAY 

EDIBLES 10% OFF





THIRSTY THURSDAYS

10% OFF ALL   D R I N K S 



FRIDAY



420 SPECIAL  - 

BUY 4 1/8S RECEIVE 20% OFF EACH 1/8

SHATTERDAY SATURDAY - ALL CONCENTRATES 10% OFF

SUNDAY - ALL VAPES and CARTRDIGES 10% OFF



HAPPY HOUR SPECIAL :

** WEDNESDAY ONLY  4:20-620pm receive 20% off if you follow us on instagram!**





Here at AHHS, we are educated and knowledgable about our products.
We are committed to providing our members with the best quality cannabis and natural alternatives to treat their pain with a large selection of the highest quality cannabis at reasonable prices. 
We are dedicated to keeping our members safe, discreet and comfortable while providing them with the very best products and medicines. We have the best staff of highly trained and caring individuals.
We carry the largest variety of smokeable and non smokeable products in California.



Medical Retail
M10-17-0000106-TEMP
Adult-Use Retail
A10-17-0000040-TEMP',
                'latitude' => '34.0906030',
                'longitude' => '-118.3602417',
                'address' => '7828 Santa Monica Boulevard',
                'state' => 'California',
                'city' => 'West Hollywood',
                'postal_code' => '90046-5303',
                'country' => 'United States',
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 01:48:20',
                'updated_at' => '2018-05-21 01:48:21',
            ),
            5 => 
            array (
                'id' => '0a91aea0-5d24-11e8-8b3e-69e8fe1094f1',
                'name' => 'Moby Dick',
                'section' => 'product',
                'slug' => 'chronic-pain-relief-center-moby-dick',
                'avatar' => NULL,
                'featured_img' => 'uploads/products/featured/4PUKUIZ13FA0QJ0oguKcJOBKBJbcNt8IfHZLGg6q.jpeg',
                'description' => NULL,
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => NULL,
                'state' => NULL,
                'city' => NULL,
                'postal_code' => NULL,
                'country' => NULL,
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 18:23:21',
                'updated_at' => '2018-05-21 18:23:22',
            ),
            6 => 
            array (
                'id' => '0d110020-5c97-11e8-baa0-77de3285a3b7',
                'name' => 'Strain Balboa Caregivers',
                'section' => 'shop',
                'slug' => 'strain-balboa-caregivers',
                'avatar' => 'uploads/business/avatars/shops/GhvKv2dQ3cQQakp2QHegABTCnKGV5zjvRZjG6S3g.jpeg',
                'featured_img' => 'uploads/business/featured/shops/WCAFqziNf5jLAoSMqa4I6Fo82RkRU4rHl9hDiYQI.jpeg',
                'description' => '21627 DEVONSHIRE ST. CHATSWORTH CA 91311. PRE-ICO & PROP D COMPLIANT ATM ON SITE  OPEN 365 DAYS A YEAR: NEW SHOP HOURS: 8AM - 10PM!!!!!!!

AS OF JANUARY 3RD, 2018 SALES OF ALL PRODUCTS AT STRAIN BALBOA CAREGIVERS WILL BE SUBJECT TO ALL APPLICABLE STATE AND LOCAL TAXES. THE TAXES ARE NOT YET REFLECTED IN OUT MENU PRICING. 

WE ARE NOW SERVING 21+ WITH VALID ID!

FACEBOOK - STRAIN BALBOA CAREGIVERS
INSTAGRAM - @STRAIN_CARES
TWITTER - @STRAINBALBOA

WEEKLY SPECIALS:
EARLY BIRD SPECIAL: 8AM-9AM EVERY MORNING
MUCHIE MONDAY: 15% OFF EDIBLES (value 20$ or more)
TANK TUESDAY: 5$ OFF ANY FULL GRAM CARTRIDGES (excluding banzai)
WAX WEDNESDAY: 10$ OFF ALL NUG RUNS AND LIVE RESINS, 5$ OFF ALL POPCORN AND TRIM RUNS, 10$ GRAMS OF WAX AVAILABLE
THURSDAY: ALL TOP SHELF FLOWER @ 30/8th (no premiums)
FADED FRIDAY: A MIX OF MYSTERY SPECIALS ON EVERYTHING!, 10$ GRAMS OF WAX AVAILABLE ALL DAY

SHATTERDAY: 10$ OFF ALL NUG RUNS AND LIVE RESINS, 5$ OFF ALL POPCORN AND TRIM RUNS, EXTRA SPECIALS ON PREPACKED CONCENTRATES, 10$ GRAMS OF WAX AVAILABLE ALL DAY
HASHY SUNDAY: 5$ OFF ALL BRAND NAME PREPACK HASH, 2G SPECIALS ON ALL REGULAR TOP SHELF HASH (cannot combine with other specials) *** ALSO COLLEGE STUDENTS, VETERANS, & PATIENTS WITH PROPER I.D. ARE ELIGIBLE FOR A 5% DISCOUNT (EVERYDAY)

MAY PATIENT APPRECIATION DAYS:

5/4 BLOOM 4-7PM
5/4 PALOMAR 5-7PM
5/4 UPSIDE EDIBLES 5-8PM
5/5 NATIV 4-7PM
5/6 CRU CANNABIS 12-3PM
5/8 ACES 4-7
5/11 BRASS KNUCKLES 4-7PM
5/12 STICK E VAPE 1-4PM
5/12 PAPA & BARKLEY 12-3PM
5/18 PRESTIGE CBD 5-7PM
5/18 STICK E VAPE 12-3PM & 4-7PM
5/19 ACES 4-7PM 
5/19 3 LEAF 1-4PM
5/19 DR.NORMS 10-12PM
5/25 BLOOM 4-7PM',
                'latitude' => '34.2574610',
                'longitude' => '-118.6013395',
                'address' => '21627 Devonshire Street',
                'state' => 'California',
                'city' => 'Los Angeles',
                'postal_code' => '91311-2902',
                'country' => 'United States',
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 01:34:06',
                'updated_at' => '2018-05-21 01:34:08',
            ),
            7 => 
            array (
                'id' => '10baff50-5d23-11e8-9071-6b61272c0f90',
                'name' => 'Private Reserve',
                'section' => 'product',
                'slug' => 'chronic-pain-relief-center-private-reserve',
                'avatar' => NULL,
                'featured_img' => 'uploads/products/featured/EK9WqnAJlU2Wb8BSNwkFSLOyp7M6p9nY4y6s2cS8.jpeg',
                'description' => NULL,
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => NULL,
                'state' => NULL,
                'city' => NULL,
                'postal_code' => NULL,
                'country' => NULL,
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 18:16:22',
                'updated_at' => '2018-05-21 18:16:23',
            ),
            8 => 
            array (
                'id' => '11de81c0-5d24-11e8-a60a-af0e3b318c5a',
                'name' => 'XJ-13',
                'section' => 'product',
                'slug' => 'chronic-pain-relief-center-xj-13',
                'avatar' => NULL,
                'featured_img' => 'uploads/products/featured/tW3r4WnbkYvGOcrSZEb844KwpiB8eUikKQ8FIwp5.jpeg',
                'description' => NULL,
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => NULL,
                'state' => NULL,
                'city' => NULL,
                'postal_code' => NULL,
                'country' => NULL,
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-21 18:23:33',
                'updated_at' => '2018-05-21 18:23:35',
            ),
            9 => 
            array (
                'id' => '15f735a0-5b29-11e8-b6db-cf404d232ec0',
                'name' => 'Exhalence',
                'section' => 'shop',
                'slug' => 'exhalence',
                'avatar' => 'uploads/business/avatars/shops/5KfpGho736bzHmACPj7TeHH7yxL1GAq9ucH09y6Z.jpeg',
                'featured_img' => 'uploads/business/featured/shops/XJU61dFadUy10tAw5R6CTnh481Eu0XyROiMTF7C4.jpeg',
                'description' => 'WE\'RE OFFICIALLY OPEN FOR ADULT USE! Now accepting adult use 21+ and medical patients 18+.

*ATTENTION!* All prices listed below and on our menu DO NOT include tax.. Thank you!

- 1/8ths up to $34, add $5 to upgrade to 5 grams

- 1/8ths $45 and up, add $10 to upgrade to 5 grams 

All purchases over $40 get to spin the wheel for a prize or coupon! * 

* Weekly Specials *

*Conditions apply - must donate 0.25 cents to our rotating local charity to receive discount.

- Munchie Monday - 15% off all edibles -

- Topical Tuesday - 15% off all lotions, rubs and creams -

- Wellness Wednesday - 15% off all CBD products -

- Thirsty Thursday - 15% off ALL drinks (7 varieties, various flavors) -

- Flashy Friday - 15% off on all bongs and pipes -

- Shatterday - 15% off all our waxes and rosins -

- Smokey Sunday - Over $20 purchase, get 3 joints for .25 cent donation to a local charity.

HIGH from Exhalence!

We are a recreational and medical marijuana dispensary presented by BOO-KU, located in Sun Valley. Having 30+ strains of cannabis at all times, where each and every bud is carefully hand-selected before being displayed on our shelves. We carry the widest selection of fire in Los Angeles. We proudly represent our signature strain KS OG, which grows in the highly-controlled environment of #ExhalenceGarden using exclusively organic and all-natural nutrients, displayed right from our store. We have everything from edibles to beauty supplies to pet products. Serving Los Angeles based patients since 2006, our ultimate mission and responsibility is providing our patients the best cannabis products in the industry with premium-quality service. Our highly trained and professional staff is ready to help you find the medication most suitable for your needs. Active military, Veterans, Seniors (65+), and disabled patients will receive a 10% discount.

You can follow the cultivation process, daily specials and the Exhalence lifestyle at instagram.com/exhalencela or directly from our store at 10467 Roscoe Blvd, Sun Valley, CA 91352. We are located right off the 5 freeway (from North: 2 mins off Sunland exit; from South: right off Glenoaks exit).

P.S. Bring your friends because we have LOTS of parking!! Refer a friend and get 5 joints with a .25 cent donation to a local rotating charity 

Vendors - Please call or email before you would like to come set up an appointment with a manager. up an appointment with a manager, appointments are preferred in the morning or early afternoon.

M10-18-0000262-TEMP, A10-18-0000219-TEMP',
                'latitude' => '34.2218551',
                'longitude' => '-118.3595633',
                'address' => '10467 Roscoe Boulevard',
                'state' => 'California',
                'city' => 'Los Angeles',
                'postal_code' => '91352',
                'country' => 'United States',
                'social' => NULL,
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-19 05:54:25',
                'updated_at' => '2018-05-19 05:54:27',
            ),
            10 => 
            array (
                'id' => '16cc4060-5ae8-11e8-9fc1-15a823f411fe',
                'name' => '#1 Suspect Extracts',
                'section' => 'brand',
                'slug' => '1-suspect-extracts',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            11 => 
            array (
                'id' => '16d62320-5ae8-11e8-99ed-953af61609cb',
                'name' => '1 World Medicinals',
                'section' => 'brand',
                'slug' => '1-world-medicinals',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            12 => 
            array (
                'id' => '16d6c3c0-5ae8-11e8-a5d3-0dd9a63b0d23',
                'name' => '1906 New Highs',
                'section' => 'brand',
                'slug' => '1906-new-highs',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            13 => 
            array (
                'id' => '16d90570-5ae8-11e8-8f8b-fb87367bcd9d',
                'name' => '2020 Creations',
                'section' => 'brand',
                'slug' => '2020-creations',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            14 => 
            array (
                'id' => '16d96770-5ae8-11e8-b743-b9e22572136b',
                'name' => '2020 Future Pre Rolls',
                'section' => 'brand',
                'slug' => '2020-future-pre-rolls',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            15 => 
            array (
                'id' => '16d9c490-5ae8-11e8-a0fb-d526c1241216',
                'name' => '2020 Knockout Pre Roll Sticks',
                'section' => 'brand',
                'slug' => '2020-knockout-pre-roll-sticks',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            16 => 
            array (
                'id' => '16da2220-5ae8-11e8-b4eb-b59c46343621',
                'name' => '2020 Medi Mudd',
                'section' => 'brand',
                'slug' => '2020-medi-mudd',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            17 => 
            array (
                'id' => '16da8560-5ae8-11e8-93e9-f5001d6412e3',
                'name' => '2020 Private Reserve Pre Rolls',
                'section' => 'brand',
                'slug' => '2020-private-reserve-pre-rolls',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            18 => 
            array (
                'id' => '16dae1b0-5ae8-11e8-ab66-e7697c1962f1',
                'name' => '23 Oils',
                'section' => 'brand',
                'slug' => '23-oils',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            19 => 
            array (
                'id' => '16db4720-5ae8-11e8-90c2-a379c249a3c6',
            'name' => '24 KARAT EXTRACTIONS (CANADA)',
                'section' => 'brand',
                'slug' => '24-karat-extractions-canada',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            20 => 
            array (
                'id' => '16db9d10-5ae8-11e8-abbc-8dfd36c72ed0',
                'name' => '24K Concentrates',
                'section' => 'brand',
                'slug' => '24k-concentrates',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            21 => 
            array (
                'id' => '16dbf8a0-5ae8-11e8-90e4-892460e7c5f4',
                'name' => '2WNTY3',
                'section' => 'brand',
                'slug' => '2wnty3',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            22 => 
            array (
                'id' => '16dc5a40-5ae8-11e8-802d-6d488194d9c5',
                'name' => '4 LOVE OIL',
                'section' => 'brand',
                'slug' => '4-love-oil',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            23 => 
            array (
                'id' => '16dcba10-5ae8-11e8-aaa5-09aad8b5eae3',
                'name' => '41 Wax Co.',
                'section' => 'brand',
                'slug' => '41-wax-co',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            24 => 
            array (
                'id' => '16dd3b70-5ae8-11e8-9553-3f017d39ffb6',
                'name' => '420 Vapor',
                'section' => 'brand',
                'slug' => '420-vapor',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            25 => 
            array (
                'id' => '16dda280-5ae8-11e8-a260-6d4bba23dc2b',
                'name' => '420 Yummies',
                'section' => 'brand',
                'slug' => '420-yummies',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            26 => 
            array (
                'id' => '16de08c0-5ae8-11e8-9cbb-f71212250ffa',
                'name' => '5-Hour High Co.',
                'section' => 'brand',
                'slug' => '5-hour-high-co',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            27 => 
            array (
                'id' => '16de6c40-5ae8-11e8-b3f9-b52d3daab228',
                'name' => '5150 Wax Rolls',
                'section' => 'brand',
                'slug' => '5150-wax-rolls',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            28 => 
            array (
                'id' => '16ded480-5ae8-11e8-aa01-b3b1cef5c200',
                'name' => '7 Points Oregon',
                'section' => 'brand',
                'slug' => '7-points-oregon',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            29 => 
            array (
                'id' => '16df2df0-5ae8-11e8-9794-f5c17bff39c4',
                'name' => '710 Errl Pharm',
                'section' => 'brand',
                'slug' => '710-errl-pharm',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            30 => 
            array (
                'id' => '16df8d00-5ae8-11e8-a3aa-551215e28da8',
                'name' => '710 Kingpen',
                'section' => 'brand',
                'slug' => '710-kingpen',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            31 => 
            array (
                'id' => '16e002e0-5ae8-11e8-b444-c750fd030157',
                'name' => '710 Labs',
                'section' => 'brand',
                'slug' => '710-labs',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            32 => 
            array (
                'id' => '16e07180-5ae8-11e8-926d-73aca51295fa',
                'name' => '805 BUDDHA BLISS',
                'section' => 'brand',
                'slug' => '805-buddha-bliss',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            33 => 
            array (
                'id' => '16e0d570-5ae8-11e8-94ab-5984abdc9b50',
                'name' => '831 Organiks',
                'section' => 'brand',
                'slug' => '831-organiks',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            34 => 
            array (
                'id' => '16e14ad0-5ae8-11e8-ac4c-f729cd111ff0',
                'name' => '831 Quality',
                'section' => 'brand',
                'slug' => '831-quality',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            35 => 
            array (
                'id' => '16e1b7f0-5ae8-11e8-b15f-77f4d03499a6',
                'name' => '9 Planet Moonbites',
                'section' => 'brand',
                'slug' => '9-planet-moonbites',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            36 => 
            array (
                'id' => '16e21320-5ae8-11e8-9c6f-2fb8199317e7',
                'name' => 'Ablis Sparkling Green',
                'section' => 'brand',
                'slug' => 'ablis-sparkling-green',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            37 => 
            array (
                'id' => '16e26ab0-5ae8-11e8-bcd7-1703ca9e1cda',
                'name' => 'Above Top Shelf',
                'section' => 'brand',
                'slug' => 'above-top-shelf',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            38 => 
            array (
                'id' => '16e2c480-5ae8-11e8-9eee-9d48429a3f7c',
                'name' => 'Absolute Cannabis Seeds',
                'section' => 'brand',
                'slug' => 'absolute-cannabis-seeds',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            39 => 
            array (
                'id' => '16e32550-5ae8-11e8-95c0-d3ecf05bed64',
                'name' => 'Absolute Terps',
                'section' => 'brand',
                'slug' => 'absolute-terps',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            40 => 
            array (
                'id' => '16e38020-5ae8-11e8-ac6f-8f8ddf9b1004',
                'name' => 'AbsoluteXtracts',
                'section' => 'brand',
                'slug' => 'absolutextracts',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            41 => 
            array (
                'id' => '16e3e0d0-5ae8-11e8-b8de-11a612b3dfc4',
                'name' => 'ACE Seeds',
                'section' => 'brand',
                'slug' => 'ace-seeds',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            42 => 
            array (
                'id' => '16e44310-5ae8-11e8-9ab6-71f2e88cdc49',
                'name' => 'ACME Elixirs',
                'section' => 'brand',
                'slug' => 'acme-elixirs',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            43 => 
            array (
                'id' => '16e4a390-5ae8-11e8-a02a-79ee6522493e',
                'name' => 'Advanced Extracts',
                'section' => 'brand',
                'slug' => 'advanced-extracts',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            44 => 
            array (
                'id' => '16e508c0-5ae8-11e8-baf2-412f377269d2',
                'name' => 'Aftermath Cannabis',
                'section' => 'brand',
                'slug' => 'aftermath-cannabis',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            45 => 
            array (
                'id' => '16e57350-5ae8-11e8-aea0-dd3af1721cb6',
                'name' => 'Agua De Flor',
                'section' => 'brand',
                'slug' => 'agua-de-flor',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            46 => 
            array (
                'id' => '16e5edd0-5ae8-11e8-ac95-916e3ebfb01b',
                'name' => 'Aims Horticulture',
                'section' => 'brand',
                'slug' => 'aims-horticulture',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            47 => 
            array (
                'id' => '16e65230-5ae8-11e8-8518-9753f732d443',
                'name' => 'Alaf Farms',
                'section' => 'brand',
                'slug' => 'alaf-farms',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            48 => 
            array (
                'id' => '16e72240-5ae8-11e8-8d32-1d75acee6fe3',
            'name' => 'ALAIR Vaporizers (CANADA)',
                'section' => 'brand',
                'slug' => 'alair-vaporizers-canada',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            49 => 
            array (
                'id' => '16e78df0-5ae8-11e8-99b0-b7ff179e9664',
                'name' => 'Alaskan Built Seeds',
                'section' => 'brand',
                'slug' => 'alaskan-built-seeds',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            ),
            50 => 
            array (
                'id' => '16e7ea70-5ae8-11e8-8898-b301526013d3',
                'name' => 'Alchemy by Dark Heart',
                'section' => 'brand',
                'slug' => 'alchemy-by-dark-heart',
                'avatar' => '',
                'featured_img' => '',
                'description' => '',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'address' => '',
                'state' => '',
                'city' => '',
                'postal_code' => '',
                'country' => '',
                'social' => '',
                'featured' => 0,
                'verified' => 0,
                'rating' => 0,
                'deleted_at' => NULL,
                'created_at' => '2018-05-18 22:09:09',
                'updated_at' => '2018-05-18 22:09:09',
            )
        ));
    }
}